INSERT INTO answers (question_id, answer_text, is_correct) VALUES
(1, 'public, private, protected', false),
(1, 'public, private, protected, default', true),
(1, 'public, private, internal', false),
(1, 'public, protected, internal, private', false),
(2, 'Изменяет исходную строку', false),
(2, 'Возвращает новую строку', true),
(2, 'Удаляет часть строки', false),
(2, 'Сравнивает строки', false),
(3, 'General Computing', false),
(3, 'Global Cache', false),
(3, 'Graphics Controller', false),
(3, 'Garbage Collector - сборщик мусора', true),
(4, 'Создание зависимостей внутри класса', false),
(4, 'Внедрение зависимостей извне', true),
(4, 'Удаление зависимостей', false),
(4, 'Кэширование зависимостей', false),
(5, 'Heap (объекты), Stack (примитивы и ссылки), Metaspace (метаданные классов)', true),
(5, 'RAM, ROM, Cache', false),
(5, 'Young, Old, Permanent', false),
(5, 'Только Heap и Stack', false),
(6, 'EXISTS всегда быстрее', false),
(6, 'JOIN работает только с двумя таблицами', false),
(6, 'JOIN может дублировать строки, EXISTS нет', true),
(6, 'Нет разницы', false);